
version: '3.7'

services:
  front:
    ports:
      - "${PORT_PROD}:80"
    volumes:
      - "${WEB_ROOT}/${DOMAIN_NAME}/prod/content:/app/wp-content"
      - wordpress:/var/www/html

  cron:
    env_file:
      - prod/web.env
    volumes:
      - "${WEB_ROOT}/${DOMAIN_NAME}/prod/content:/app/wp-content"
      - wordpress:/app

  db:
    env_file:
      - prod/db.env

  web:
    env_file:
      - prod/web.env
    volumes:
      - "${WEB_ROOT}/${DOMAIN_NAME}/prod/content:/var/www/html/wp-content"
      - wordpress:/var/www/html
